### ISSUE TITLE
Web installer goes to a deadlink

### ISSUE THREAD

**Issue by b1pb1p** [PlakarLabs/docs.plakar.io#2]
The web installer option for Plakar is broken : 

http://plakar.io/install.sh gives a 404.

**Comment by poolpOrg** [comment]
Where did you see that link ? 😊

It's https:// but good catch, the http -> https redirect should have worked

**Comment by b1pb1p** [comment]
![CleanShot 2024-10-04 at 23 35 45@2x](https://github.com/user-attachments/assets/77242dae-c77d-4026-bdcb-9131d7e214f0)

**Comment by poolpOrg** [comment]
I'll fix the doc shortly but https works for me, I'll check the logs

![image](https://github.com/user-attachments/assets/7b2980ca-807a-404c-918b-5250c423fc30)

**Comment by poolpOrg** [comment]
Also just to clarify this is not the real installer, this one builds executable but after first release it'll distribute pre-built binaries 😊

**Comment by b1pb1p** [comment]
sorry faulty here 👇 got a nice 404 from nginx 
![CleanShot 2024-10-04 at 23 44 29@2x](https://github.com/user-attachments/assets/eee6fb6c-88f5-4914-a48e-efc31a6c5b68)

**Comment by poolpOrg** [comment]
my bad, I removed the instruction to use the web installer for now:

plakar.io is only whitelisted for @misterflop and I at the moment until we have the landing page ready, so instructions that point to that website are bound to fail at the moment :-)
